version: '3.8'

services:
  sql1:
    build:
      dockerfile: DATABASE/Dockerfile
    ports:
      - "1433:1433"
    container_name: sql1
    networks:
      - my_bridge_network

  register-api:
    build: 
      dockerfile: API/Dockerfile
    ports:
      - "8080:80"
      - "8081:433"
    container_name: register-api
    networks:
      - my_bridge_network
    depends_on:
      - sql1

networks:
  my_bridge_network:
    driver: bridge
