version: '3.8'

services:
  sql1:
    build:
      context: .
      dockerfile: "./database/Dockerfile"
    ports:
      - "1433:1433"
    container_name: sql1
  register-api:
    build: 
      context: .
      dockerfile: "./1 - register - api/Dockerfile"
    ports:
      - "80:80"